site_name: Progenetix Documentation
site_description: 'Documentation for the Progenetix oncogenomics resource'
site_author: Michael Baudis
copyright: '&copy; Copyright 2022, Michael Baudis and progenetix.org'
repo_name: 'progenetix-web'
extra_css:
  - css/extra.css

repo_url: https://github.com/progenetix/progenetix-web
edit_uri: edit/main/docs/

###############################################################################

nav:
  - Documentation Home: index.md
  - 'Progenetix News': news/index.md
  - Use Case Examples: use-cases.md
  - 'Services & API': services.md
  - 'Classifications, Ontologies & Standards': classifications-and-ontologies.md
  - Publication Collection: publication-collection.md
  - Changelog: changelog.md
  - 'Beacon+ &amp; bycon': beaconplus.md
  - Technical Notes: technical-notes.md
  - Progenetix Data: http://progenetix.org
  - 'Baudisgroup @ UZH': http://info.baudisgroup.org

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_gh_links:
      user: progenetix
      repo: progenetix.github.io
  - tables

###############################################################################

theme:
  # name: readthedocs
  name: material
  palette:
    primary: deep orange
  favicon: img/site-logo-topright.png
  logo: img/site-logo-topright.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  custom_dir: overrides
      
plugins:
  - search
  # - pdf-export:
  #     combined: true

extra:
  blog:
    dir: news
    author: Baudisgroup
#    author_image: img/site-logo-topright.png
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
    
# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
