site_name: Progenetix Documentation
site_description: 'Read the Docs Documentation for the Progenetix oncogenomics resource'
site_author: Michael Baudis
copyright: '&copy; Copyright 2022, Michael Baudis and progenetix.org'
repo_name: 'beacon-schema-2'

#extra_css: [css/theme_overrides.css]

markdown_extensions:
  - admonition
#  - attr_list

theme: readthedocs

# Options
